name: app_name
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # translation
  easy_localization: ^3.0.0
  # generate assets and language paths
  flutter_gen: ^4.1.6
  # responsive ui
  flutter_screenutil: ^5.3.1
  # verify code
  pin_code_fields: ^7.3.0
  # server locator
  kiwi: ^4.0.2
  # state management
  flutter_bloc: ^8.0.1
  # dealing with API
  dio: ^4.0.4
  # images slider
  carousel_slider: ^4.0.0
  dots_indicator: ^2.1.0
  # cache data
  shared_preferences: ^2.0.13
  # logger
  quick_log: ^5.2.1
  # svg images
  flutter_svg: ^1.0.3
  # for items or notification numbers
  badges: ^2.0.2
  image_picker: ^0.8.4+11
  # to rotate image
  flutter_exif_rotation: ^0.5.0
  animate_do: ^2.1.0
  flutter_local_notifications: ^9.4.0
  path_provider: ^2.0.9
  #firebase
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  pull_to_refresh: ^2.0.0
  awesome_dialog: ^2.2.1
  screenshot: ^1.2.3
  permission_handler: ^10.0.0
  image_cropper: ^3.0.0
  swipe_cards: ^1.0.0
  dotted_border: ^2.0.0+2
  share_plus: ^4.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/svg_images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/
    - assets/translations/

  fonts:
    - family: Black
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
    - family: ExtraLight
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf